version: '3.1'

services:
  mojaBazaSpremnik:
    image: 'mtadijalfer/or-labosi:v1'
    container_name: mojaBazaSpremnik
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"